name: SimpleHomeSystem
version: '${project.version}'
main: at.lav.SimpleHomeSystem
api-version: '1.19'
load: STARTUP
authors: [lav]
description: Ein simples Home-System.
website: https://apply.landania.dev/de/
commands:
  home:
    permission: simplehomesystem.home
    description: Teleport to home.
    usage: /home
  sethome:
    permission: simplehomesystem.sethome
    description: Set home locations.
    usage: /sethome
  delhome:
    permission: simplehomesystem.delhome
    description: Delete your home locations
    usage: /delhome
  homes:
    permission: simplehomesystem.homes
    description: Show all your homes
    usage: /homes